name: Update cpusim in portfolio

on: workflow_dispatch

permissions:
  contents: write

jobs:
  update-app:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the portfolio repository (main)
      - name: Checkout portfolio
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2. Prepare working directories
      - name: Create temp and build folders
        run: |
          mkdir temp
          mkdir -p build/apps/4bt_cpu_sim

      # 3. Checkout the portfolio repository (gh-pages) into temp
      - name: Checkout portfolio
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: temp/gh_pages
          fetch-depth: 1

      # 4. Checkout 4bt_cpu_sim repo into temp
      - name: Checkout 4bt_cpu_sim repo
        uses: actions/checkout@v4
        with:
          repository: Mark-Platts/4-bit-CPU-JS-own-arch
          path: temp/4bt_cpu_sim
          fetch-depth: 1

      # 5. Copy portfolio root files â†’ build/ (excluding unwanted folders)
      - name: Copy portfolio files into build
        run: |
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='build' \
            --exclude='temp' \
            ./ build/

      # 6. Copy previosu app files into build/apps and delete cpusim
      - name: Copy previous app folder to build and delete cpusim
        run: |
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            temp/gh_pages/apps build/apps/
          rm -rf build/apps/4bt_cpu_sim/

      # 7. Copy current cpusim files into build/apps/cpusim
      - name: Copy current cpusim into apps folder
        run: |
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            temp/4bt_cpu_sim/ build/apps/4bt_cpu_sim/

      # 8. Deploy build/ folder to the deploy branch
      - name: Deploy build/ to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
  
